<?php
/*
Template Name:  Theme: Features Three Style.
Preview Image:  #
Descriptions:   #
*/
?>
[vc_section full_width="stretch_row" css=".vc_custom_1499312142784{padding-top: 45px !important;padding-bottom: 45px !important;}"][vc_row][vc_column offset="vc_col-lg-offset-3 vc_col-lg-6 vc_col-md-offset-3 vc_col-md-6"][vc_custom_heading text="Theme Typography." font_container="tag:h2|text_align:center" google_fonts="font_family:Raleway%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900|font_style:800%20bold%20regular%3A800%3Anormal"][vc_custom_heading text="Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..." font_container="tag:p|text_align:center" google_fonts="font_family:Raleway%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900|font_style:300%20light%20regular%3A300%3Anormal"][/vc_column][/vc_row][vc_row css=".vc_custom_1499311381053{margin-top: 45px !important;}"][vc_column width="1/3" css=".vc_custom_1499312170964{margin-bottom: 30px !important;}"][vc_featured_box heading_text="800+ Google Fonts" content_text="<a href='https://fonts.google.com/' target='_blank'>https://fonts.google.com/</a>
<div>Find and use high quality fonts for your website</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" horizontal_alignment="left" icon="fa fa-font"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312196033{margin-bottom: 30px !important;}"][vc_featured_box heading_text="TypeKit" content_text="<a href='https://typekit.com/' target='_blank'>https://typekit.com/</a>
<div>Get access to a huge bundle of premiums fonts.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" horizontal_alignment="left" icon="fa fa-keyboard-o"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312209134{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Fontstruct" content_text="<a href='https://fontstruct.com/' target='_blank'>https://fontstruct.com/</a>
<div>Create your fonts from the ground up, pixel by pixel.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" horizontal_alignment="left" icon="fa fa-strikethrough"][/vc_column][/vc_row][vc_row][vc_column width="1/3" css=".vc_custom_1499312241377{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Typecast" content_text="<a href='https://typecast.com/' target='_blank'>https://typecast.com/</a>
<div>Create visual and semantic designs that put type final.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" horizontal_alignment="left" icon="fa fa-glide-g"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312251005{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Font Squirrel" content_text="<a href='https://typekit.com/' target='_blank'>https://fontsquirrel.com/</a>
<div>Take advantage of the best database of free fonts.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" horizontal_alignment="left" icon="fa fa-magnet"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312266829{margin-bottom: 30px !important;}"][vc_featured_box heading_text="1001 Fonts" content_text="<a href='http://1001fonts.com/' target='_blank'>http://1001fonts.com/</a>
<div>Scan a huge library of fonts for personal or commercial use.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" horizontal_alignment="left" icon="fa fa-bookmark-o"][/vc_column][/vc_row][/vc_section][vc_section full_width="stretch_row" css=".vc_custom_1499312300240{padding-top: 45px !important;padding-bottom: 45px !important;background-color: #f2f2f2 !important;}"][vc_row][vc_column offset="vc_col-lg-offset-3 vc_col-lg-6 vc_col-md-offset-3 vc_col-md-6"][vc_custom_heading text="Theme Typography 2." font_container="tag:h2|text_align:center" google_fonts="font_family:Raleway%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900|font_style:800%20bold%20regular%3A800%3Anormal"][vc_custom_heading text="Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..." font_container="tag:p|text_align:center" google_fonts="font_family:Raleway%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900|font_style:300%20light%20regular%3A300%3Anormal"][/vc_column][/vc_row][vc_row equal_height="yes" css=".vc_custom_1499312566359{margin-top: 45px !important;}"][vc_column width="1/3" css=".vc_custom_1499312664932{margin-bottom: 30px !important;}"][vc_featured_box heading_text="800+ Google Fonts" content_text="<a href='https://fonts.google.com/' target='_blank'>https://fonts.google.com/</a>
<div>Find and use high quality fonts for your website</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" graphic_shape="circle" horizontal_alignment="right" icon="fa fa-font" css=".vc_custom_1499312683538{padding: 30px !important;background-color: #ffffff !important;}"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312196033{margin-bottom: 30px !important;}"][vc_featured_box heading_text="TypeKit" content_text="<a href='https://typekit.com/' target='_blank'>https://typekit.com/</a>
<div>Get access to a huge bundle of premiums fonts.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" graphic_shape="circle" horizontal_alignment="right" icon="fa fa-keyboard-o" css=".vc_custom_1499312702498{padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 30px !important;padding-left: 30px !important;background-color: #ffffff !important;}"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312209134{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Fontstruct" content_text="<a href='https://fontstruct.com/' target='_blank'>https://fontstruct.com/</a>
<div>Create your fonts from the ground up, pixel by pixel.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" graphic_shape="circle" horizontal_alignment="right" icon="fa fa-strikethrough" css=".vc_custom_1499312720751{padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 30px !important;padding-left: 30px !important;background-color: #ffffff !important;}"][/vc_column][/vc_row][vc_row][vc_column width="1/3" css=".vc_custom_1499312241377{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Typecast" content_text="<a href='https://typecast.com/' target='_blank'>https://typecast.com/</a>
<div>Create visual and semantic designs that put type final.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" graphic_shape="circle" horizontal_alignment="left" icon="fa fa-glide-g" css=".vc_custom_1499312765060{padding: 30px !important;background-color: #ffffff !important;}"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312251005{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Font Squirrel" content_text="<a href='https://typekit.com/' target='_blank'>https://fontsquirrel.com/</a>
<div>Take advantage of the best database of free fonts.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" graphic_shape="circle" horizontal_alignment="left" icon="fa fa-magnet" css=".vc_custom_1499312793414{padding: 30px !important;background-color: #ffffff !important;}"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312266829{margin-bottom: 30px !important;}"][vc_featured_box heading_text="1001 Fonts" content_text="<a href='http://1001fonts.com/' target='_blank'>http://1001fonts.com/</a>
<div>Scan a huge library of fonts for personal or commercial use.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" graphic_shape="circle" horizontal_alignment="left" icon="fa fa-bookmark-o" css=".vc_custom_1499312822466{padding: 30px !important;background-color: #ffffff !important;}"][/vc_column][/vc_row][/vc_section][vc_section full_width="stretch_row" css=".vc_custom_1499313012705{padding-top: 45px !important;padding-bottom: 45px !important;}"][vc_row][vc_column offset="vc_col-lg-offset-3 vc_col-lg-6 vc_col-md-offset-3 vc_col-md-6"][vc_custom_heading text="Theme Typography 3." font_container="tag:h2|text_align:center" google_fonts="font_family:Raleway%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900|font_style:800%20bold%20regular%3A800%3Anormal"][vc_custom_heading text="Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..." font_container="tag:p|text_align:center" google_fonts="font_family:Raleway%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900|font_style:300%20light%20regular%3A300%3Anormal"][/vc_column][/vc_row][vc_row equal_height="yes" css=".vc_custom_1499312566359{margin-top: 45px !important;}"][vc_column width="1/3" css=".vc_custom_1499312664932{margin-bottom: 30px !important;}"][vc_featured_box heading_text="800+ Google Fonts" content_text="<a href='https://fonts.google.com/' target='_blank'>https://fonts.google.com/</a>
<div>Find and use high quality fonts for your website</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" icon="fa fa-font" css=".vc_custom_1499313192509{padding-top: 35px !important;padding-right: 30px !important;padding-bottom: 35px !important;padding-left: 30px !important;background-color: #f2f2f2 !important;border-radius: 10px !important;}"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312196033{margin-bottom: 30px !important;}"][vc_featured_box heading_text="TypeKit" content_text="<a href='https://typekit.com/' target='_blank'>https://typekit.com/</a>
<div>Get access to a huge bundle of premiums fonts.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" icon="fa fa-keyboard-o" css=".vc_custom_1499313221971{padding-top: 35px !important;padding-right: 30px !important;padding-bottom: 35px !important;padding-left: 30px !important;border-radius: 10px !important;}"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312209134{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Fontstruct" content_text="<a href='https://fontstruct.com/' target='_blank'>https://fontstruct.com/</a>
<div>Create your fonts from the ground up, pixel by pixel.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" icon="fa fa-strikethrough" css=".vc_custom_1499313264824{padding-top: 35px !important;padding-right: 30px !important;padding-bottom: 35px !important;padding-left: 30px !important;background-color: #f2f2f2 !important;border-radius: 10px !important;}"][/vc_column][/vc_row][vc_row][vc_column width="1/3" css=".vc_custom_1499312241377{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Typecast" content_text="<a href='https://typecast.com/' target='_blank'>https://typecast.com/</a>
<div>Create visual and semantic designs that put type final.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" icon="fa fa-glide-g" css=".vc_custom_1499313321142{padding-top: 35px !important;padding-right: 30px !important;padding-bottom: 35px !important;padding-left: 30px !important;}"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312251005{margin-bottom: 30px !important;}"][vc_featured_box heading_text="Font Squirrel" content_text="<a href='https://typekit.com/' target='_blank'>https://fontsquirrel.com/</a>
<div>Take advantage of the best database of free fonts.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" icon="fa fa-magnet" css=".vc_custom_1499313410161{padding-top: 35px !important;padding-right: 30px !important;padding-bottom: 35px !important;padding-left: 30px !important;background-color: #f2f2f2 !important;border-radius: 10px !important;}"][/vc_column][vc_column width="1/3" css=".vc_custom_1499312266829{margin-bottom: 30px !important;}"][vc_featured_box heading_text="1001 Fonts" content_text="<a href='http://1001fonts.com/' target='_blank'>http://1001fonts.com/</a>
<div>Scan a huge library of fonts for personal or commercial use.</div>
" heading_color="#222222" content_color="#444444" graphic_color="#ffffff" graphic_background_color="#ff3a4e" icon="fa fa-bookmark-o" css=".vc_custom_1499313354479{padding-top: 35px !important;padding-right: 30px !important;padding-bottom: 35px !important;padding-left: 30px !important;background-color: #ffffff !important;}"][/vc_column][/vc_row][/vc_section]
